### ISSUE TITLE
[Request] Duplicate and Drag to Move

### ISSUE THREAD

**Issue by davidhawbecker** [Saibot393/notebook#1]
This is an awesome little utility and I can not believe it took someone this long to create something this all encompassing, yet effective. There is so much potential here for GM's to quickly organize and track things in game. Right not the three things I can see right off the bat that would be helpful would be:

1. Make it so you can right click and duplicate a note.
2. Make it  so you can drag and reorder notes.
3.  Not sure if it's necessary with your filtering and search functions but folders may be nice for organizing a lot of notes. 

Minor, things. But this really is cool. Well done and thanks for sharing with the community.

**Comment by Saibot393** [comment]
Glad to hear that you enjoy the module. Regarding your points:
1. This is planned and will most likely be part of the next update (1.2.0)
2. This is already possible, you can reorder notes by draging the black title bar
3. This is currently in develoment but will probably still take a bit of time. The feature will be the focus of the next update (1.2.0)

**Comment by Saibot393** [comment]
I have just released v1.2.0. The new version includes both folders and an option to copy notes (shift + right-click).
I have decided to make a few changes to the folders, compared to the core foundry folders, to make it easier to use them "on the fly", which i think fits the nature of the notes a bit better. Therefore feedback regarding the folders is especially welcome.
