### ISSUE TITLE
Feature Request:A button that is actively displayed to the player

### ISSUE THREAD

**Issue by kagangtuya-star** [Saibot393/notebook#2]
Function request. Add a button to the notebook that has become an independent window. This button's purpose is to actively display the notebook to the player.
Sometimes I want to emphasize some key things, it's more direct to pop up a notebook for the players proactively than to let them find it on their own.

Just like the 'Show Players' in the journal.If it can also change permissions, that would be even better!
![PixPin_2024-06-01_12-32-24](https://github.com/Saibot393/notebook/assets/73411104/7a17230a-dcea-43e5-b47d-fdacc4d9f79d)

Thank you for your work!

**Comment by Saibot393** [comment]
Good idea, i think i will add it to the permission menu

**Comment by Saibot393** [comment]
I have added a "show to users" option to to the note permission menu for GMs with v1.4.0
