### ISSUE TITLE
Sidebar size behaves weirdly

### ISSUE THREAD

**Issue by Peach774** [Saibot393/notebook#4]
This might be a conflict with dorako UI, but the UI width cant be changed until i hide the sidebar and make it come back. This resets whenever the game is restarted and sometimes when reloading. The odd thing is that the size you drag to will change to whatever it should've been based on where you were dragging even though it didn't show any change until you refreshed. Theres no errors in the console, it just doesnt work right.

**Comment by Saibot393** [comment]
I think i know what is happening. Due to the additional symbol in the sidebar i had to slightly increase the sidebar width. Thid change gets applied when the side bar is first rendered, this then overwrites the custom width set by dorako ui. I will look into a fix as soon as possible.

**Comment by Saibot393** [comment]
The bug should now be fixed with v1.4.1
