### ISSUE TITLE
Missing from toolbar

### ISSUE THREAD

**Issue by Beastduke2** [Saibot393/notebook#5]
The notebook has gone missing from my tool bar on the top right of the screen along with it went all my DM notes. Note book as a module is in my active modules and as of now i have no way of accessing the module. 
![image_2024-07-28_175814035](https://github.com/user-attachments/assets/f2cafee3-60d0-4fc9-9ce8-20c7d8be6631)

**Comment by Saibot393** [comment]
are there any errors in the console (F12)? Did you recently install/update any modules and does the notebook tab reapear when deactivating these modules?

**Comment by Beastduke2** [comment]
There are 39 errors and 17 warnings. I performed a update of foundry, of D&D 5e, and all modules before starting my session.

**Comment by Saibot393** [comment]
I think i found the bug. It should now be fixed with v1.4.2. Sorry for the inconvenience.

**Comment by Beastduke2** [comment]
the issue has been fixed. thank you!
