### ISSUE TITLE
List Note typing speed

### ISSUE THREAD

**Issue by Egochecks** [Saibot393/notebook#6]
On the List Note, the note seems to be constantly refreshing as I type. If I type at a normal speed, the cursor will jump back and will often not register typed characters. It seems to be some sort of refresh. Maybe the focus or the flexbox? Couldn't figure it out from the console. If this is a new issue, it might be a conflicting module. Just wanted to raise it.

**Comment by Saibot393** [comment]
I will look into it

**Comment by Saibot393** [comment]
I tried to implement a fix for this behaviour with v1.4.3. In case this fix does not work, which browser are you using?

**Comment by Egochecks** [comment]
Thanks. I just downloaded the module today but I'll check my module version. I was on Chrome.  
 
  On Wed, Jul 31, 2024 at 6:16 PM, ***@***.***> wrote:   


I tried to implement a fix for this behaviour with v1.4.3. In case this fix does not work, which browser are you using?

**Comment by Egochecks** [comment]
I had v1.4.2; it's fixed in v1.4.3. Thank you.

**Comment by Saibot393** [comment]
Good to hear
