### ISSUE TITLE
Right click not popping menu out.

### ISSUE THREAD

**Issue by 4m2c4bl3** [Saibot393/notebook#7]
When right clicking on other tabs (actors, journals, etc), they pop out into separate views. Right clicking on notebook causes nothing to happen.

**Comment by Saibot393** [comment]
I am planning on adding that feature in the future, might take some time though

**Comment by Saibot393** [comment]
I have added the tab popout with v1.5.0

**Comment by 4m2c4bl3** [comment]
thank you!
